/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all targets */
        get: operations["getTargets"];
        put?: never;
        /** Create a new target */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{targetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the target */
                targetId: string;
            };
            cookie?: never;
        };
        /** Get a single target by ID */
        get: operations["getTargetById"];
        /** Update an existing target */
        put: operations["updateTarget"];
        post?: never;
        /** Delete a target */
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Coordinates: {
            /**
             * Format: double
             * @description Latitude coordinate
             * @example 32.0853
             */
            latitude: number;
            /**
             * Format: double
             * @description Longitude coordinate
             * @example 34.7818
             */
            longitude: number;
            /**
             * Format: double
             * @description Altitude in meters
             * @example 150.5
             */
            altitude: number;
        };
        /**
         * Format: double
         * @description Frequency value (433/915 MHz or 2.4/5.2/5.8 GHz)
         * @example 2.4
         * @enum {number}
         */
        Frequency: 433 | 915 | 2.4 | 5.2 | 5.8;
        Target: {
            /**
             * Format: uuid
             * @description Unique identifier
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: double
             * @example 32.0853
             */
            latitude: number;
            /**
             * Format: double
             * @example 34.7818
             */
            longitude: number;
            /**
             * Format: double
             * @example 150.5
             */
            altitude: number;
            frequency: components["schemas"]["Frequency"];
            /**
             * Format: double
             * @description Speed in m/s
             * @example 25
             */
            speed: number;
            /**
             * Format: double
             * @description Bearing in degrees
             * @example 180
             */
            bearing: number;
            /**
             * @description IPv4 address
             * @example 192.168.1.1
             */
            ip_address: string;
        };
        TargetCreate: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: double */
            altitude: number;
            frequency: components["schemas"]["Frequency"];
            /** Format: double */
            speed: number;
            /** Format: double */
            bearing: number;
            ip_address: string;
        };
        TargetUpdate: {
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            altitude?: number;
            frequency?: components["schemas"]["Frequency"];
            /** Format: double */
            speed?: number;
            /** Format: double */
            bearing?: number;
            ip_address?: string;
        };
        TargetListResponse: {
            targets: components["schemas"]["Target"][];
            /** @example 1 */
            count: number;
        };
        CreateResponse: {
            /** Format: uuid */
            id: string;
            /** @example Target created successfully */
            message: string;
        };
        MessageResponse: {
            /** @example Operation successful */
            message: string;
        };
        ErrorResponse: {
            /** @example Target not found */
            error: string;
            /** @example 404 */
            status: number;
        };
        ValidationError: {
            /** @example Validation failed */
            error: string;
            /**
             * @example {
             *       "bearing": "Must be between 0 and 360"
             *     }
             */
            details: {
                [key: string]: string;
            };
            /** @example 400 */
            status: number;
        };
        HealthResponse: {
            /** @example healthy */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetListResponse"];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Target created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    getTargetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the target */
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            /** @description Target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the target */
                targetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetUpdate"];
            };
        };
        responses: {
            /** @description Target updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the target */
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
